### ISSUE TITLE
Undocumented breaking change (Cannot visit <Enum>)

### ISSUE THREAD

**Issue by bsedat** [beerlington/classy_enum#53]
I noticed that https://github.com/beerlington/classy_enum/commit/963ac910a26d7b6d7f6a0899c9f9f677ffd0cbde removed some visitor support and changed the specs. I upgraded to the 4.0 gem version and am seeing that lines similar to `Dog.where(:breed => Breed.build('golden_retriever'))` now error. I didn't see any mention of that change in the CHANGELOG, but maybe I'm missing something?

**Comment by beerlington** [comment]
@bsedat that's a good point, this should be added to the changelog since it was intentional and breaking. The reason I pulled it out was because the hacks required to make it work relied on some arel internals that were inconsistent between different versions of Active Record.

I would recommend converting the enum object to a string if possible instead of passing it directly to the query.

**Comment by bsedat** [comment]
No worries, less hacks and more portability are awesome :smile:. Thanks for your work on the gem!

**Comment by bsedat** [comment]
:+1: Thanks!
