### ISSUE TITLE
Question: Using classy enum to query with AR?

### ISSUE THREAD

**Issue by tisba** [beerlington/classy_enum#54]
I'm a bit irritated on how to use classy enum correctly in some cases.

Given the following enum definitions:

```ruby
class House::PictureType < ClassyEnum::Base; end

class House::PictureType::Summer < House::PictureType; end
class House::PictureType::Winter < House::PictureType; end
```

I cannot use classy enum in AR queries like this:

```ruby
Pictures.where(kind: House::PictureTypes::Summer)
```

Do I understand correctly that the right way to do this is to instantiate a enum and call `#to_s`?

```ruby
Pictures.where(kind: House::PictureTypes::Summer.new.to_s)
```

This feels very wired, mainly because I think of enums as constant types (value objects) and it makes no sense to instantiate them. Also, is there a "better" way to get the enums value representation then calling `#to_s`? Why can't I call `House::PictureTypes::Summer.to_s` directly as *every instance* of it will always return `summer` (AFAIK)

**Comment by beerlington** [comment]
Hi @tisba,

When working with Classy Enum, you have to consider that the enums are really a hybrid of an enum and a plain Ruby class. When Active Record doesn't know how to properly convert a Ruby object to the correct format, it blows up with a "Cannot visit ..." error. Unfortunately Active Record doesn't expose a way to make querying easier which is why it must be explicitly converted to a string. If I wanted to support this in Classy Enum, I'd have to hack the ARel internals, which I did at one time, but Classy Enum broke every time the ARel internals were refactored. It was a huge pain to maintain.

I don't want to override `.to_s` on the enum class because I don't want to change the expected `.to_s` behavior on a Ruby class.

There isn't really a "better" to do it, but I'd maybe recommend one of these:

A shorter way to do what you'e got in your last example would be:

```ruby
Pictures.where(kind: 'summer')
```

If you don't want to use a string directly, you can also use the parent enum class like so:

```ruby
Pictures.where(kind: House::PictureType[:summer].to_s)
```

Note that in the last example, this is equivalent to `House::Picture.find(:summer).to_s` and returns the enum instance instead of the class.

**Comment by tisba** [comment]
hey @beerlington,

thanks for the quick answer. IMO you could outline this in the README, because I think it's not so unusual to work with enums this way :)

Another quick question: If I read the code correctly, I have to override `#to_s` in order to change the "value" behind an enum, correct?

Thanks!

**Comment by beerlington** [comment]
Thanks for the feedback. I'll update it soon. Yes if you want to have the class name be different than what is stored in the database, you'll want to override `#to_s`. Just keep in mind that you'll need to update the values that already exist in the database, otherwise Classy Enum won't be happy if it finds an enum value it doesn't understand.

**Comment by tisba** [comment]
Great. I'll leave it up to you to close this issue (maybe as a reminder to change the README?). Anyways, thanks again!

**Comment by beerlington** [comment]
There's another related issue that I've been leaving open to remind myself. Looks like I need to get on it! https://github.com/beerlington/classy_enum/issues/53

**Comment by beerlington** [comment]
Just updated the readme, let me know if you think it could be improved. https://github.com/beerlington/classy_enum#active-record-querying
