### ISSUE TITLE
Add support for validation :on and :if options

### ISSUE THREAD

**Issue by pineapplethief** [beerlington/classy_enum#57]
As it stands, `classy_enum_attr` macro isn't very flexible, and if I want to customize validation a bit with `if` and `on` options, I have to monkey_patch method and delete validation defined by the gem. I guess something like `validate_on:` and `validate_if` options for this method would be pretty useful and easy to add, I could prepare a PR if you don't mind.

**Comment by beerlington** [comment]
Did you mean to close this?

**Comment by pineapplethief** [comment]
@beerlington Yes, kind of read contribution guidelines concerning no more new features after I opened the issue

**Comment by beerlington** [comment]
I'd be interested in this because it doesn't seem like a new feature as much as just delegating something that already exists to active record. This gem has been around for 6 years and this request hasn't come up before, so I am curious what the use case is. It seems like if you were to persist a record with an invalid enum, things would break because it would try loading a class that didn't exist. How are you using it?

**Comment by pineapplethief** [comment]
Client has a requirement to not validate fields in some cases, but, giving
it second thought I realize you are right and I can achieve what I want by
using allow_blank: true everywhere and defining context dependent presence
validations by myself. Sorry to bother you)

2016-03-29 23:14 GMT+10:00 Peter Brown notifications@github.com:

**Comment by beerlington** [comment]
No worries! Don't be afraid to open another issue if you run into any problems with that.
